version: '3'

services:
    coreference:
        container_name: coreference
        image: cnstntn/coref_dp_cpu:latest
        restart: always
        ports:
            - 3023:3000
    syntax_ner:
        container_name: syntax_ner
        image: cnstntn/syntax_ner_dp_0.14:latest
        restart: always
        ports:
            - 3021:3021
            - 3022:3022
        command: >
            bash -c "python -m deeppavlov riseapi ru_syntagrus_joint_parsing -p
            3021 & python -m deeppavlov riseapi ner_rus_bert -p 3022"
