version: '3'

services:
    coreference:
        container_name: coreference
        image: cnstntn/coref_dp_cpu:latest
        restart: always
        ports:
            - 3000:3001
    syntax_ner:
        container_name: syntax_ner
        image: cnstntn/dp_0.14:latest
        restart: always
        ports:
            - 3002:3002
            - 3003:3003
        command: >
            bash -c "python -m deeppavlov riseapi ru_syntagrus_joint_parsing -p 3002
            & python -m deeppavlov riseapi ner_rus_bert -p 3003"


